### ISSUE TITLE
Support Japanese Language

### ISSUE THREAD

**Issue by tkashi** [aws-solutions/serverless-bot-framework#27]
### Is your feature request related to a problem? Please describe. ###
No Japanese language supported.

### Describe the feature you'd like ###
Japanese is now supported in Lex. So, I am very happy if the Serverless Bot Framework also supports it.

**Comment by mohsenari** [comment]
Thanks @tkashi for your interest in Serverless Bot Framework. I will bring this idea of adding more Amazon Lex supported languages to my team and will get back to you.

**Comment by yosawad** [comment]
I'm interested in this solution, but the lack of Japanese support is an obstacle.
Amazon Lex is now available in Japanese, are there any plans for this solution?

**Comment by mohsenari** [comment]
@yosawad @tkashi with the latest merge #48 and #49 the solution now supports Japanese language.
